### ISSUE TITLE
Allow automatic group creation on recursive add

### ISSUE THREAD

**Issue by hamiltont** [nosarthur/gita#101]
Use case: I've got tons of git repos I need to manage, but they are already nicely grouped into folders (e.g. `Work/Client-5/Project-4/Service-1/<code>`). Currently I'm using `gita add -r` to add them all, then grouping using bash (e.g. `for i in $(gita ls); do echo "target-group" | gita group add $i; done`

With #93 we got a lovely `-r` flag on the add command. Would it be possible to add a `--auto-group` flag that only works if `-r` was passed. Preferably, this would cause groups to be created after the add, with one group per parent folder (e.g. a repo stored at `Foo/Bar/Code` would be in two different groups, `Foo`, `Bar`. It would also be fine if the tool auto-created groups as `Foo` and `Foo-Bar` (to avoid issues where subfolders might have the same names as other projects). 

Thoughts?

**Comment by nosarthur** [comment]
In your example `Work/Client-5/Project-4/Service-1/<code>`, is `Service-1` the git repo? And you want to run `gita add Work -r --auto-group` to get the following groups?

- work: it contains all repos
- work-client-1
  - work-client1-project1: it contains all the service repos
  - work-client1-project2
  - ...
- work-client-2 
- ...

**Comment by hamiltont** [comment]
Exactly!

**Comment by nosarthur** [comment]
I think this behavior is reasonable

**Comment by nosarthur** [comment]
Didn't get a chance to work on this yet

**Comment by nosarthur** [comment]
This is related to #82 

After that is done, maybe this is no longer needed? You can just make main repos and enter into them to see only the relevant repos

**Comment by melMass** [comment]
Scoped workspace is a great idea! In my personal workflow it's even better!

**Comment by nosarthur** [comment]
Suppose we do `gita add -r --auto-group a-folder` (maybe `-a` for short), the subordinate repos have hash in the form of `(a-group, sub-dir, sub-sub-dir, repo-dir)`, thus we can make a `groups=defaultdict(list)`, loop over the newly found repos, and add them to groups whose names are all possible partial hashes. 

Seems easy enough

**Comment by nosarthur** [comment]
already released in v0.15.1

I still need to clean up the group name clashes. Let me know if you find any other issues.
