### ISSUE TITLE
Add some additional options for group subcommand

### ISSUE THREAD

**Issue by hamiltont** [nosarthur/gita#102]
Few different ideas, all related to groups: 
 1. For `group add`, would it be possible to add a `--to <group>` flag, so it is easier to script the tool. Currently it requires the user to stop and enter the group name
 1. Would a `group rename` be hard? 
 1. Would an `ls` alias on `ll` be hard e.g. `gita group ls`. This would mirror the main gita API

Thanks for a useful tool!

**Comment by nosarthur** [comment]
These are all easy to do.

I was thinking of doing 1. 

For 3, `gita group ls` would give the group names without repos. Is that what you expect?

**Comment by hamiltont** [comment]
Thanks!! Looking forward to using the updated tool 🙂

>
