### ISSUE TITLE
A no colour option for when running through either a script or cron.

### ISSUE THREAD

**Issue by ygworldr** [nosarthur/gita#106]
I am using gita to backup some repositories so need to run `gita ll` (just to see what will change) then do `gita pull`. Because this runs through cron, I get some ugly control characters instead of colours. Would it be possible to add a `--no-colours` option?

Thank you

**Comment by nosarthur** [comment]
That's surely possible. 

Do you want to always turn off the colors or only for the cron jobs? If you don't want to see colors at all, I could also make the color on/off via the `gita info` mechanism

**Comment by ygworldr** [comment]
Just for the cron job is fine. I like pretty colours otherwise! If I get the time, I might do a PR but I am pretty swamped so…

**Comment by nosarthur** [comment]
please try version 0.11.7

**Comment by nosarthur** [comment]
In v0.12.2 I will change the shortcut of `--no-colors` from `-n` to `-C`

**Comment by ygworldr** [comment]
This works great. Many thanks indeed!
