### ISSUE TITLE
Colourblind-friendly Palette

### ISSUE THREAD

**Issue by bjohnnyd** [nosarthur/gita#110]
Hi,

I am not able to distinguish the green and yellow cases when local is the same or when local is behind.  Due to being colour blind this combination of colours is making it impossible for me to tell when local is behind remote.  This is especially true when using `gita ll` when they appear sequentially sometimes.

It would be great if the colours could be changed or if there was a colour-blind-friendly palette that can be enabled permanently? I guess even a flag or extra column in the output of `gita ll` would work in this case.  

The red, green and yellow combination (in that hue) might be a problem in general for colour blind people as they can appear sequential in the output.  The colour scheme in my terminal has been working fine for me thus far and have not had this issue before.  

Thank you for a great tool.

**Comment by nosarthur** [comment]
That's a great suggestion. To be honest, I sometimes cannot tell the difference myself, depending on the color scheme of the terminal ... 

There are 2 things we can do here:

- let the user customize the colors
- add an extra column to spell out the local-remote relation explicitly

I will explore both of them

**Comment by nosarthur** [comment]
please try 0.12.1

it allows user to change the coloring via `gita color set <situation> <color>`

u can get the available colors from `gita color`

**Comment by bjohnnyd** [comment]
This is perfect now.  I just set the more often ones as the bold version and it works very nice. 

Great work, thank you.

**Comment by nosarthur** [comment]
Great, I’ll close it for now
