### ISSUE TITLE
Allow execution of nested `git` commands

### ISSUE THREAD

**Issue by nwu63** [nosarthur/gita#114]
Hi, thanks again for this excellent tool. The motivation comes from trying to get `gita` to checkout the latest tag for an entire group. The command is `git describe --abbrev=0 --tags` to get the latest tag, and `git checkout <tag>` to checkout the tag. This can be combined in bash with
```
git checkout $(git describe --abbrev=0 --tags)
```
I'm wondering if it's possible to execute this for multiple repos. Both the `cmds.yml` approach and using superman did not work for me.

As a related issue, once a tag is checked out, `gita ll` simply shows `HEAD` for the status column. Is there a way to get it to display the checked out tag? I understand it's in detached head status, but `git status` shows `HEAD detached at v2.2.1` for example so there should be a way to fetch and display this information somehow.

**Comment by nosarthur** [comment]
Would a 2-step solution work for you? Run the `git describe` first on one repo, say

```
gita super <repo-name> describe ...
```

 then 

```
gita super checkout <tag-name>
```

**Comment by nwu63** [comment]
Unfortunately, the problem is that the tags are repo-specific, so different repos would have different tags that need to be checked out. I guess currently `gita` can't directly call `os.system()` or anything like that?

**Comment by nosarthur** [comment]
I see. 

It uses `subprocess` or `asyncio` to execute the git commands. I need to think about how to deal with this situation

**Comment by nwu63** [comment]
Sure no worries. It would be great to be able to execute the same bash commands in a bunch of repos, but maybe that's not really the intent of this tool.

**Comment by nwu63** [comment]
Would you be opposed to allowing execution of arbitrary shell commands in multiple repos at once? Something like `subprocess.run([SHELL, '-c', COMMAND])` or equivalent. That way I could pass in a single string `"git checkout $(git describe --abbrev=0 --tags)"` and have that work in multiple repos.

Also, to follow up on a question from before. When a tag is checked out, is it possible for `gita ll` to show the tag rather than just `HEAD`? The p10k extension I use for zsh does this currently so I'm sure there is a way, since `git status` will show the name of the tag also.

**Comment by nosarthur** [comment]
For your first suggestion, we can either add a command `gita shell`, or override `gita super`,

Adding an option to display tag sound good, thanks for the suggestion!

**Comment by nwu63** [comment]
> For your first suggestion, we can either add a command `gita shell`, or override `gita super`,

`gita super` would be good except for the fact that it requires executing two `git` commands, with the second command depending on the return from the first (and the value will be repo-dependent). So maybe having an explicit `gita shell` command which allows shell expansion would be better.

**Comment by nosarthur** [comment]
`gita shell` is in 0.12.7, let me know if it works for your tag check out

**Comment by nwu63** [comment]
Thanks for putting in the work. I just tried it out and
```
gita shell <group> git describe --abbrev=0 --tags | xargs git checkout
```
failed with `fatal: not a git repository (or any parent up to mount point /)`. I'm assuming this is because my shell was trying to run the first half of the command, then pipe that whole output to `xargs` and then run `git checkout` wherever I was at.

Surrounding the `shell` command with quotes failed with a subprocess error `No such file or directory: 'git describe --abbrev=0 --tags | xargs git checkout'`.

However, after modifying line 255 of `__main__.py` by adding `shell=True`, I was able to run
```
gita shell <group> "git describe --abbrev=0 --tags | xargs git checkout"
```
successfully for all repos under <group>.

I'm not sure if you want to incorporate this change but I do prefer the syntax where the entire string is passed through `subprocess`, rather than some weird shell expansion happening that I don't fully understand.

**Comment by nosarthur** [comment]
I have no problem with `shell=True`. Do you want to make a PR?

**Comment by nwu63** [comment]
Will do!

**Comment by nosarthur** [comment]
related to #161

**Comment by nosarthur** [comment]
@nwu63 With v0.14.2 you will be able to define that command in `cmds.yml` like this

```
myco:
  cmd: git describe --abbrev=0 --tags | xargs git checkout
  allow_all: true
  shell: true
  help: some help
```

**Comment by nwu63** [comment]
Awesome, thanks for letting me know!
