### ISSUE TITLE
Tag 0.11.9 doesn't contain freeze and clone sub-commands

### ISSUE THREAD

**Issue by wigust** [nosarthur/gita#116]
Hi.  First of all thank you for the project!

https://github.com/nosarthur/gita/releases mentions 0.11.9 contains freeze and clone sub-commands, but it doesn't.

IMHO it would be great to create a new tag based on current master.  ;-)

Oleg.

**Comment by nosarthur** [comment]
You are right, 0.11.9 doesn't have it. I have corrected the release message, thanks!

Did you try installing the latest, i.e., 0.12.4? 

```
pip3 install -U gita
```

These two commands were actually added in #99 version 0.12.3

**Comment by wigust** [comment]
I didn't try pip3 command, thanks for the hint. ;-)  I close the issue.
