### ISSUE TITLE
check if the new name is already in use when `rename` a repo

### ISSUE THREAD

**Issue by nosarthur** [nosarthur/gita#148]
Currently, the repo originally has the name is thrown way. I think we should reject such `rename` request

**Comment by YoYoChaico** [comment]
Hey, How would you want it to be rejected? error message?

**Comment by YoYoChaico** [comment]
i added the change, but unable to push. 
Im new to this.. could you explain me please what i should do next?

**Comment by nosarthur** [comment]
Error message sounds good. To contribute to a github project, you need to fork the project, modify your forked local copy, then make a pull request. The project owner will review the code, and if all goes well, merge in the PR

See this article for more details:
https://www.dataschool.io/how-to-contribute-on-github/

**Comment by YoYoChaico** [comment]
ok thanks! 
and how should the error message be returned. i cant find another example for an error message..

**Comment by nosarthur** [comment]
You can print it to screen for now.
