### ISSUE TITLE
Add --preserve-path to gita clone

### ISSUE THREAD

**Issue by jmourelos** [nosarthur/gita#153]
Hi, I just found out about gita and it looks very useful. I would like to use it to clone the same set of repositories across multiple machines by using `gita clone`. I group these repositories in a couple of directories. Since `gita freeze` already saves the absolute path for each repository, my idea would be to add a flag `--preserve-path` to `gita clone` that would change the behaviour to clone the repositories to the absolute paths saved by `gita freeze` instead of cloning them to the current directory.

It sounds to me like a simple change, so I could implement it if you think the idea makes sense for the project.

**Comment by nosarthur** [comment]
This is actually the original request and I was too lazy to implement it...

Please go ahead, thank you!

**Comment by nosarthur** [comment]
published in 0.13.8

Thanks for the contribution!
