### ISSUE TITLE
group name should not clash with repo name

### ISSUE THREAD

**Issue by nosarthur** [nosarthur/gita#158]
Check any clash when `add` group and `rename` group

**Comment by aryanag7** [comment]
Hey, I'm a beginner in open source and would like to contribute to your project. Can u let me know how should I get started? @nosarthur

**Comment by nosarthur** [comment]
To contribute to a github project, you need to fork the project, modify your forked local copy, then make a pull request. The project owner will review the code, and if all goes well, merge in the PR

See this article for more details:
https://www.dataschool.io/how-to-contribute-on-github/
