### ISSUE TITLE
Add instructions in release notes on upgrading

### ISSUE THREAD

**Issue by nwu63** [nosarthur/gita#163]
I just updated to the latest version, and noticed that none of my groups were being recognized by `gita`. The release notes seem to suggest that the `repo_path` file has been moved, but it wasn't clear to me that I just had to rename `repo_path` to `repos.csv` since I wasn't sure if `repo_path` was in the expected CSV format. Everything turned out fine, but it would be great if there are instructions in the release notes (or elsewhere) that explains the process for updating from a previous version if there are any breaking changes. This would help users who are updating.

An even better approach would be to handle this automatically in the code (i.e. detect if `repo_path` exists and the CSV file does not, then perform the migration silently) but that may be too involved. I think just a one-liner instruction would be great.

Also, were there any other changes? I just want to double check that I didn't miss anything.

**Comment by nosarthur** [comment]
You are absolutely correct. I didn't make a release on github on every release, only once in 8 or 9 releases. I will make it a habit to do it for every release in the future. 

As for the groups, they have changed to `groups.csv` under `~/.config/gita/`, see #143

**Comment by nosarthur** [comment]
Just made the release note for v0.14.2 on github. See https://github.com/nosarthur/gita/releases/tag/v0.14.2

**Comment by nwu63** [comment]
Thanks! I didn't even notice that the version didn't match what I installed, I just assumed that the latest on GitHub is also the latest on PyPI.

Would you mind editing `v0.13.6` release notes to mention that to upgrade, users should rename the `repo_path` file? And similarly for the `groups.csv` change in `v0.14.2`. This would make it easier for users who want to upgrade, so they don't find out that some custom configurations are mysteriously broken.

**Comment by nosarthur** [comment]
Updated, thanks for the heads up. Let me know if you have further suggestions!

https://github.com/nosarthur/gita/releases/tag/v0.13.6
https://github.com/nosarthur/gita/releases/tag/v0.14.2

**Comment by nwu63** [comment]
Looks good, thanks for the prompt responses!
