### ISSUE TITLE
groups.csv fails to parse on windows.

### ISSUE THREAD

**Issue by semiirs** [nosarthur/gita#169]
Steps to reproduce:
* On a windows machine, run "gita group add someRepo -n test_group"

Actual result:
* groups.csv is generated with an extra newline. This causes a parsing error later - see [gita_parsing_error_windows.log](https://github.com/nosarthur/gita/files/6762812/gita_parsing_error_windows.log)

stackoverflow describes the issue - https://stackoverflow.com/questions/3191528/csv-in-python-adding-an-extra-carriage-return-on-windows and the suggested fix (add newlines='') helped me.

Environment:
* OS: Windows 10
* python: 3.7
* gita version - 0.14.9

**Comment by nosarthur** [comment]
Thanks @semiirs 

I added this test, adding 1 repo to a new group
https://github.com/nosarthur/gita/commit/1f5d44ebd6e8d29b721c17142d34f582b628fd55

Strangely, it passed ... Does this bug depend on the number of repos added?
https://github.com/nosarthur/gita/runs/2990267879

**Comment by nosarthur** [comment]
I added your suggested fix in v0.15.0 anyways (already available). Let me know if that solves your problem
