### ISSUE TITLE
Feature request: Make repo name on superman mode optional

### ISSUE THREAD

**Issue by seqizz** [nosarthur/gita#17]
I wanted to checkout to master branch on all my repos but couldn't find a fast way. Is it possible to skip repository name and run something like `gita super checkout master` to run this command on all available repos?
Thx

**Comment by nosarthur** [comment]
Very neat suggestion. I could benefit from this feature too. My employer's repos are branched as year-quarters, and it'll be convenient to checkout the same branch for all repos.

I think it should be easy to implement since a similar mechanism already exists in `gita fetch`, which fetches for all

**Comment by nosarthur** [comment]
seems to work now in 0.7.1

**Comment by seqizz** [comment]
Thanks, works great.

Another small suggestion, this can be default for most of the commands. This way one wouldn't even need to use super every time. E.g.:

```
gita fetch
gita status
gita pull # Which I guess currently not a thing
gita checkout somebranch # This also
```

**Comment by nosarthur** [comment]
I created #20 so one can customize any command/alias into this special mode

Btw, what do you mean by `gita pull` is not a thing right now?

**Comment by seqizz** [comment]
Ah sorry I wasn't being clear. I meant pure usage of `gita pull` is not a thing and we need to give repo name. It can behave similar to `gita fetch` and pull all if there was no repo name supplied.

**Comment by nosarthur** [comment]
I see. I will change the default `pull` behavior in 0.7.2, together with the customization change

I also wonder why you didn't comment on `status` as not a thing, since only `fetch` is in this special mode right now.

**Comment by seqizz** [comment]
Apparently I forgot :smile:
