### ISSUE TITLE
Package is missing yaml dependency

### ISSUE THREAD

**Issue by tuukkamustonen** [nosarthur/gita#176]
```
$ pip install gita
...
Successfully installed gita-0.15.2
$ gita
...
ModuleNotFoundError: No module named 'yaml'
```

Indeed, it's missing `install_requires` in [setup.py](https://github.com/nosarthur/gita/blob/master/setup.py).

You'll probably want to depend on [PyYAML](https://pypi.org/project/PyYAML)?

**Comment by nosarthur** [comment]
Thanks @tuukkamustonen 

It once depends on pyyaml but I forgot to delete one import statement. Will fix it soon

**Comment by nosarthur** [comment]
please check v0.15.3

**Comment by tuukkamustonen** [comment]
Indeed, the error is gone. Thanks for the speedy actions! 🎉
