### ISSUE TITLE
Explicitly define repos in Superman mode

### ISSUE THREAD

**Issue by tuukkamustonen** [nosarthur/gita#177]
Having the Superman mode is great :)

However, let's say I run:

```shell
gita super some-repo-that-doesnot-exist-or-maybe-i-typo-it tag -l
```

What happens is `gita` doesn't detect the first parameter (`some-repo-that-doesnot-exist-or-maybe-i-typo-it`) as repo and executes the whole `some-repo-that-doesnot-exist-or-maybe-i-typo-it tag -l` as git command, iterating _all_ repos (and failing for each).

I understand the ease of not having to do something like:

```shell
gita super -c some-repo -c another-repo tag -l
```

But that would avoid the risk of executing repo name as git command.

Alternatively:

```shell
gita super some-repo another-repo "tag -l"
```

Here you could take the last parameter as the git command and again avoid the problem.

What do you think?

**Comment by nosarthur** [comment]
You can source the auto completion code
https://github.com/nosarthur/gita/blob/master/.gita-completion.bash

Then the repo names can be tab-completed

**Comment by tuukkamustonen** [comment]
Yeah, it's nice to have those. But for example, I use `fish` shell so I don't have auto-completion available.

People out there might use whatever tooling and configuration to run it, some might be on Windows, and so on. So unfortunately, auto-completion won't catch this for everyone and it would be better if the tool had interface that dodged the bullet here, don't you think?

**Comment by nosarthur** [comment]
You have a valid point, we can proceed with the quoted form

**Comment by nosarthur** [comment]
We can support both the quoted and unquoted version for `gita super` and `gita shell`, so everyone can be happy.

Add a flag say `-q` to turn on the quoted version.

**Comment by nosarthur** [comment]
please try v0.16.1.2
