### ISSUE TITLE
Add `gita ll -d` for directory based listing and `gita ll -g` for group based listing

### ISSUE THREAD

**Issue by tuukkamustonen** [nosarthur/gita#182]
As discussed in https://github.com/nosarthur/gita/issues/178 it could be nice if `gita ll` could have a couple of extra modes.

Given a structure of:

```
project1/
    repoA/
project2/
    repoA/
    repoB/
```

Currently, `gita ll` does:

```
project1/repoA  master      ()
project2/repoA  master      ()
repoB           master      ()
```

But it would be nice to just list them with **directory structure**, for example `gita ll -d`:

```
project1/
    repoA  master     ()
project2/
    repoA master      ()
    repoB master      ()
```

Now I understand than gita detects the name of these repos as `project1/repoA`, `project2/repoA` and `repoB`. It's not clear in the above listing which "ID" the repos have. So maybe indicate it somehow, for example via colors, asterisk, emojis or whatever:

```
project1/
    **repoA**  master      ()
project2/
    **repoA**  master      ()
    repoB      master      ()
```

Now read would now that these highlighted ones need their parent path as reference.

Similarly, listing by groups could be nice. Let's say we had these groups:

```
project1: project1/repoA
project2: project2/repoA repoB
extragroup: project1/repoA repoB
```

`gita ll -g` would show:

```
project1:
    project1/repoA  master      ()

project2:
    project2/repoA  master      ()
    repoB           master      ()

extragroup:
    project1/repoA  master      ()
    repoB           master      ()
```

Having duplicate entries here is ok, because that's what grouping allows.

**Comment by nosarthur** [comment]
The `-d` option is troublesome to do. Maybe the `-g` already suffice?

**Comment by nosarthur** [comment]
The `-g` option is in v0.15.4.2

**Comment by tuukkamustonen** [comment]
I'm testing with 0.15.6 now. I'm using structure of:

```
temp/
    project1/
        repoA
    project2/
        repoA
        repoB
```

Here:

```
$ cd temp
$ gita add -a .
Found 4 new repo(s).
Created 3 new group(s).
$ gita ll
temp:
   - project1/repoA
   - repoB
   - project2/repoA
   - temp  <--- see below
temp-project1:
   - project1/repoA
temp-project2:
   - repoB
   - project2/repoA
```

It looks good, but I don't think `temp` should be inside itself?

Also, having the "main" group there brings clutter. I'm already inside the temp directory/group, so couldn't you exclude it in the listing as invoking commands with "temp" group here is really the same as just omitting it from executions?
