### ISSUE TITLE
include inital repo url in repos.csv

### ISSUE THREAD

**Issue by 4nd3r** [nosarthur/gita#192]
My usecase: I have lots of git repos in different groups and repos come and go weekly. I have multiple machines and I use `yadm` to keep all my dotfiles and other configuration in sync between all of them. As I move between computers, I also need to access all the repos.

I can manage `gita` config in `~/.config/gita` with `yadm`, but when adding new repo I have to manually do `gita freeze` and then `gita clone` in every machine. It would be cool if `repos.csv` also contains repo url and `gita` notifies if some repo is missing locally and prompts to clone it from configured location.

**Comment by nosarthur** [comment]
`gita clone -p <frozen-config>` may be what you want. It will try to clone to the prescribed locations if possible

**Comment by 4nd3r** [comment]
Yes, I understand that. My point is that git repository URL (that one you can get with `gita freeze | awk -F, '{print $1}'`) should be included in `repos.csv` (which in turn can be managed with `yadm` or any other dotfiles manager). Then `gita` can automatically clone missing repos.

**Comment by nosarthur** [comment]
Thanks for the exlanation.

Does the `gita super` traceback still exist in [0.15.8](https://github.com/nosarthur/gita/releases/tag/v0.15.8)?

I can add a check for the destination so clone is not attempted if the requested repo is already there. 

I am not familiar with `yadm`. How does adding URL to `repos.csv` solve your problem? Suppose you copy all the `~/.config/gita` content to a brand new machine, what do you do then?

**Comment by 4nd3r** [comment]
```sh
<add new repo to repo to gita etc>
yadm commit -a -m foo
yadm push

for h in host1 host2 host3 host4 host5 host6 host7 host8
do
    ssh -A "$h" yadm pull
    gita freeze | ssh -A "$h" gita clone -p /dev/stdin
done
```
