### ISSUE TITLE
`gita shell` without argument fails with UnboundLocalError: local variable 'i' referenced before assignment

### ISSUE THREAD

**Issue by sebastien-rosset** [nosarthur/gita#195]
By now I have figured `gita shell` needs to be followed by arguments, but the error message is not very user-friendly. Typing `gita shell` by itself yields the following output:

```
gita shell
Traceback (most recent call last):
  File "/usr/local/bin/gita", line 8, in <module>
    sys.exit(main())
  File "xxxxxx/gita/gita/__main__.py", line 680, in main
    args.func(args)
  File "xxxxxx/gita/gita/__main__.py", line 378, in f_shell
    cmds = ' '.join(args.man[i:])  # join the shell command into a single string
UnboundLocalError: local variable 'i' referenced before assignment
```

**Comment by nosarthur** [comment]
Please try 0.15.8

**Comment by sebastien-rosset** [comment]
Thank you!

**Comment by nosarthur** [comment]
Thanks for pointing out the issue!

**Comment by sebastien-rosset** [comment]
BTW, it seems it would be easier to understand if repos/groups and shell commands were specified using non-positional arguments, especially when repo names and/or group names are also command names. For example, consider the scenarios below: 
```
gita shell ls ls -alrt
gita shell ls pwd
gita shell git git status
```

It would be easier to parse (for the script and humans) if we had:
```
gita shell -r ls -c ls -alrt
gita shell -r ls -c pwd
gita shell -g git -c git status
```

**Comment by nosarthur** [comment]
That is a a valid concern; I am thinking of implementing #177 The command will be quoted as the last parameter
