### ISSUE TITLE
Unable to create group

### ISSUE THREAD

**Issue by sascha-andres** [nosarthur/gita#200]
When I try to create a new group I get the following errors:

    gita group add: error: argument repo: invalid choice: 'scripts' (choose from )

I call the command like this:

    gita group add: error: argument repo: invalid choice: 'scripts' (choose from )

I tried this on Windows and Linux

**Comment by nosarthur** [comment]
Your error message makes me think you don't have any repo added yet. What does `gita ll` or `gita ls` show?

**Comment by sascha-andres** [comment]
@nosarthur You're right. If I may propose something: for me adding a repo to a group was adding the folder to the group. It was not obvious for me that repo in a gita sense is something different than a repo on disk.

Maybe I missed some getting started documentation that would have made it more clear?

Anyways, I'm going to close this issue.

**Comment by nosarthur** [comment]
The concept of group came quite recently. In the early days, the git operations act either on a single repo or all repos. Thus one needs to add the repos first

Maybe you will be interested in the command `gita add -a <some folder containing repos>`. It automatically generates groups for you

```
usage: gita add [-h] [-g {home,dev,sdg}] [-r | -a | -b] paths [paths ...]

add repo(s)

positional arguments:
  paths                 repo(s) to add

optional arguments:
  -h, --help            show this help message and exit
  -g {home,dev,sdg}, --group {home,dev,sdg}
                        add repo(s) to the specified group
  -r, --recursive       recursively add repo(s) in the given path(s).
  -a, --auto-group      recursively add repo(s) in the given path(s) and create hierarchical groups based on folder structure.
  -b, --bare            add bare repo(s)
```
