### ISSUE TITLE
listing untracked content

### ISSUE THREAD

**Issue by ackermanaviation** [nosarthur/gita#209]
I'm trying to use gita to replace code I've been using to track many repos.
I need to be able to see what is not currently tracked.

I don't think there is currently any way to do this?

If not, I want to add a `gita untracked` command to show everything in the current directory and subdirectories that is not currently tracked by gita.

**Comment by nosarthur** [comment]
what about `gita add -n -a .` where `-n` is dry-run?

**Comment by nosarthur** [comment]
please try v0.16.1.1 via `pip3 install -U gita`, it seems to work on my machine

**Comment by ackermanaviation** [comment]
Hmm, this is a nice addition, however, it is limited to only finding git repos. I need to also report files and non-repos - it's how I'm tracking things that need to be done. I tried taking out the is_git test in the add repos, but i get a full directory tree. if path /home/user/doc is not tracked, i don't need to know that /home/user/doc/item1, /home/user/doc/item2, etc... are also untracked.

This may be enough of a unique case that I have to add a separate feature in my own version. I can add a pull request after I do it and you can see if you think there's any value in adding to the main
