### ISSUE TITLE
remove all current groups/repos

### ISSUE THREAD

**Issue by bcdiaconu** [nosarthur/gita#213]
when changing context would be great to be able to get rid of previously created gita repos/groups. one approach could be `gita rm *`. another one could be `gita clear`.

in the new context, one could simply run `gita add -a .` to automatically create groups and add repos. this will keep context small and easy to manage

**Comment by bcdiaconu** [comment]
By context I mean working workspace rather than gita's context. I will use workspace instead of context to avoid terminology overlapping.

I could have several tens of hundred of workspaces with a few potential groups and repos. In this scenarios, always having them all in gita, would be a hard thing to manage. Think of only running an `gita group`command. 

The proposed conceptual workflow is that when moving to a new workspace directory, that contains several groups and projects it is desirable to start with a clean gita by running a `gita rm *` or `gita clear` and than simply run a `gita add -a .`. That way all becomes simplified and focused on the current workspace, no matter what gita command.

To achieve this, always removing the files manually when changing workspace would be tedious.

**Comment by nosarthur** [comment]
`gita clear` is surely a possibility.

From your description, `gita add -a <workspace folder1> <workspace folder2> ...` seems to be the way to go. Then you can set `gita context auto`, which will automatically change context for you, based on your current working directory

**Comment by nosarthur** [comment]
The inner working of `auto` context:

When you run `gita add -a .`, the automatically-created groups  also contain 'group path' (see `~/.config/gita/groups.csv` for examples). When `auto` context is on, cwd is compared to group paths to figure out which group is the current context.

For groups not added from `gita add -a`, you can manually assign group path using `gita group add -p <some path>`. A typical usage case:

```
/enclosing-folder
  /repo1
  /repo2
  /some-other-folder
      /repo3
```
Say you manually added those 3 repos into a group, then you can also assign the enclosing folder as the group path.

**Comment by bcdiaconu** [comment]
I know about auto context. however when later want to do a push on all repos of the workspace without changing directory to root workspace, you cannot run `gita context none` and gita push. you still have to either change dir to root workspace or to know or find the group for the whole workspace. or is there any other way?

**Comment by bcdiaconu** [comment]
> workspace folder1
i was thinking more in the linke of `gita add -a <workspace>`

**Comment by bcdiaconu** [comment]
> `gita clear` is surely a possibility.
> 
> From your description, `gita add -a <workspace folder1> <workspace folder2> ...` seems to be the way to go. Then you can set `gita context auto`, which will automatically change context for you, based on your current working directory

i was thinking more in the linke of gita add -a <workspace> and all projects belonging to that workspace are populated automatically with groups created also automatically

**Comment by bcdiaconu** [comment]
> The inner working of `auto` context:
> 
> When you run `gita add -a .`, the automatically-created groups also contain 'group path' (see `~/.config/gita/groups.csv` for examples). When `auto` context is on, cwd is compared to group paths to figure out which group is the current context.
> 
> For groups not added from `gita add -a`, you can manually assign group path using `gita group add -p <some path>`. A typical usage case:
> 
> ```
> /enclosing-folder
>   /repo1
>   /repo2
>   /some-other-folder
>       /repo3
> ```
> 
> Say you manually added those 3 repos into a group, then you can also assign the enclosing folder as the group path.


I know about auto context. however when later want to do a push on all repos of the workspace without changing directory to root workspace, you cannot run gita context none and gita push. you still have to either change dir to root workspace or to know or find the group for the whole workspace. or is there any other way?

**Comment by bcdiaconu** [comment]
I started working on it here: https://github.com/nosarthur/gita/pull/214

**Comment by nosarthur** [comment]
> i was thinking more in the line of gita add -a <workspace> and all projects belonging to that workspace are populated automatically with groups created also automatically based on dir structure

This is the same as what I suggest. 

> I know about auto context. however when later one would want to do a push on all repos of the workspace with gita, without changing directory to root workspace, it cannot run gita context none followed by gita push. He still has to either change dir to root workspace or either to know or to find the group for the whole workspace

It sounds like a bug. Can you give more details? What is the procedure to trigger the problem?

Suppose you are done working on one workspace (from your description, it seems to be the same as 'context' in gita, i.e., a group). I guess at the point you want to push the changes for that group, then there are two options

1. if you know the name of the group, then `gita push <group-name>`
2. if you have `auto` context on, and you are in the right group path, then `gita push` (this requires your PR)

In this workflow, it seems `gita clear` is not really needed. But it doesn't hurt to have it.

> I have just tried and it seems gita push without a group or repo does not work actually. But gita pull does work. I think it would make sense to make it a consistent optional parameter [repo | group, ...] and also add gita clear or gita reset. what do you think?

I deliberately disallowed that for `put`, but it makes sense to let user do whatever they want.
