### ISSUE TITLE
gita drive root error on Windows

### ISSUE THREAD

**Issue by bcdiaconu** [nosarthur/gita#215]
![image](https://user-images.githubusercontent.com/23461852/151665585-108790dc-da22-4abe-bfb6-f6474d4337c1.png)

from this point on `gita group` executes successfully while `gita ll` will throw the same exception

OS: Windows 11
Gita ver: 0.16.1.2
Installed with pip

**Comment by bcdiaconu** [comment]
![image](https://user-images.githubusercontent.com/23461852/151666363-f63d4dab-0689-4d26-a37d-365d87c92986.png)

The issue lays here where it sees `parent` var definition as a relative path rather than a drive letter

**Comment by nosarthur** [comment]
I just tried it on my MBP and there was no traceback. Maybe it's specific to windows.

Does the `auto` context ever work on your machine?

**Comment by bcdiaconu** [comment]
> I just tried it on my MBP and there was no traceback. Maybe it's specific to windows.
> 
> Does the `auto` context ever work on your machine?

yes, `auto` context works on my machine. its just that i have done `gita add -a .` while cwd was `i:`

**Comment by bcdiaconu** [comment]
I have changed the `parent` value from `"I:"` to `"I:\\"` and it does not raise error anymore.

I'm thinking of adding `"\\"` if not exists and afterwards remove the trailing one. I am less experienced with Python so I would really like your opinion on it.

**Comment by nosarthur** [comment]
Did you add `\\` in `~/.config/gita/groups.csv`? What is the top-level group in that file after running `gita add -a .` at `I:`?

Does it work if you just add `\`, i.e., `I:\`?

I am not familiar with windows. For *nix machines, a `/` is guaranteed. Maybe we can add `os.sep` if it doesn't exist in the group path, when saving the group path?

**Comment by nosarthur** [comment]
What is the line that triggers the traceback? I tried this on my MBP and it doesn't error out

```
In [2]: os.path.commonpath(('I:', 'I:'))
Out[2]: 'I:'

In [4]: os.path.commonpath(('I:\\', 'I:'))
Out[4]: ''
```

**Comment by bcdiaconu** [comment]
I have replace every line in `groups.csv` similar to the following:
was:
`-MOBILE:openScale:"I:MOBILE"`
replaced with:
`-MOBILE:openScale:"I:\MOBILE"`

with this modification when I am inside a directory and do a `gita ll` will execute successfully
but if I run the same command in `I:` it will throw another exception
![image](https://user-images.githubusercontent.com/23461852/151667194-b7ef6da6-a920-4950-9b12-6e4d1b1b38f3.png)

**Comment by bcdiaconu** [comment]
> os.path.commonpath(('I:\\', 'I:'))

on windows side:
![image](https://user-images.githubusercontent.com/23461852/151667446-38644fdb-cb24-4b98-96cf-17b0fa31ff27.png)

**Comment by bcdiaconu** [comment]
tried again by deleting the two csv files and doing the same operation from within an directory, the context works properly:
![image](https://user-images.githubusercontent.com/23461852/151667577-0864f7ad-7e92-476f-b7bf-43ea5c2c1d0c.png)

**Comment by bcdiaconu** [comment]
![image](https://user-images.githubusercontent.com/23461852/151931137-f6e3f77f-aa65-4860-82cd-771fa1f5d247.png)
looking at the image above it looks like using the `Path` var type instead of `str` is the way forward as it solves a few problems. Some of the more interesting ones being solved for this issue are:
* the slashes or backslashes 
* the malformed `D:dir1` instead of correct `D:\dir1`

**Comment by nosarthur** [comment]
This seems to  be the problem: 
https://stackoverflow.com/questions/66907726/why-is-the-absolute-path-of-a-drive-letter-equal-to-the-working-directory

Currently I always strip off the trailing os separator, see `__main__.py::_path_name`. Maybe we just need to pick the other convention: always keep the trailing os separtor. I think both would work, I probably picked the current one because `# Note that os.path.commonpath has no trailing /`

Another (easier) solution could be to use [relative_to](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.relative_to), or  [is_relative_to](https://github.com/python/cpython/blob/913e340a323c7e61ae6e4acbb1312b4342657bec/Lib/pathlib.py#L822) in the `pathlib`. Maybe they handle the windows drive correctly

**Comment by bcdiaconu** [comment]
> Maybe we just need to pick the other convention: always keep the trailing os separtor.

Unfortunately I do may think that is enough. I saw that all paths are malformed eg: `d:projects` instead of either `d:/projects` or true Windows style `d:\\projects`. That is why I think this approach will only solve some usecases and this kind of problems that will be solved on one platform and create problems on another will come over and over to byte in the future. And will be like a continuous and exhausting patching process. 

I still believe that the only way to move forward in a stable way is to use what seems pretty reliable and tested `Path` class. It will require a bit more RAM (but not that much) with a great benefit in terms of stability in the long term.

**Comment by bcdiaconu** [comment]
> Another (easier) solution could be to use relative_to, or is_relative_to in the pathlib. Maybe they handle the windows drive correctly

If you have an idea on what statements to test, I will gladly do so on Windows side to make sure it is or not the way forward. I will also take a better look at them when I get a bit more time at hand.

**Comment by bcdiaconu** [comment]
I took a look at `PurePath` and it contains cross-platform functions that manipulate platform specific paths. 

To have a single code-base targeting all platforms, it is required to have cross-platform functions that manipulate cross-platform paths. 

So my conclusion is that `Path` is the way to go. Path also have a relative functionality, namely [os.path.relpath](https://docs.python.org/3/library/os.path.html#os.path.relpath)

Please let me know if you find it differently.

**Comment by nosarthur** [comment]
just curious, does it work if you simply replace `os.path.commonpath` by `os.path.commonprefix` as in the TODO comments?

**Comment by bcdiaconu** [comment]
![image](https://user-images.githubusercontent.com/23461852/152106977-8b896d2c-24d3-472d-8282-0f8bd5b8ac0e.png)
it started really promising. but ruined in the end.

**Comment by nosarthur** [comment]
what about this one?
```
def get_relative_path(kid: str, parent: str) -> Union[List[str], None]:
    """
    Return the relative path depth if relative, otherwise MAX_INT.

    Both the `kid` and `parent` should be absolute paths
    """
    if parent == "":
        return None

    p_kid = Path(kid)
    # p_kid = Path(kid).resolve()
    try:
        p_rel = p_kid.relative_to(parent)
    except ValueError:
        return None
    rel = str(p_rel).split(os.sep)
    if rel == ["."]:
        rel = []
    return rel

```

**Comment by bcdiaconu** [comment]
![image](https://user-images.githubusercontent.com/23461852/152108990-c3cc1a2f-3547-4aef-a36c-968112d6255b.png)

still some work to be done on it

**Comment by nosarthur** [comment]
that's the expected result though. can you try the true business logic?

**Comment by bcdiaconu** [comment]
> 
![image](https://user-images.githubusercontent.com/23461852/152109639-221693a7-049e-46a2-9323-130de601ac17.png)
exactly, expected results were right. but coming back with another try

**Comment by nosarthur** [comment]
these are too fake, can you `gita clear`, and then do that `gita add -a ` at `I:`?

**Comment by bcdiaconu** [comment]
`def get_relative_path_w_resolve(kid: str, parent: str) -> Union[List[str], None]:
    """
    Return the relative path depth if relative, otherwise MAX_INT.

    Both the `kid` and `parent` should be absolute paths
    """
    if parent == "" or kid == "":
        return None

    p_kid = Path(kid).resolve()
    p_parent = Path(parent).resolve()
    try:
        p_rel = p_kid.relative_to(p_parent)
    except ValueError:
        return None
    rel = str(p_rel).split(os.sep)
    if rel == ["."]:
        rel = []
    return rel
`

this however will bring expected results, if works as expected also on linux:
![image](https://user-images.githubusercontent.com/23461852/152110087-af0cc527-26a7-43a1-ae35-e49a3ba51f09.png)

**Comment by nosarthur** [comment]
I feel your test cases are a bit too unreal / strict. In reality they won't be of those variations. The absolute paths with `os.sep` are saved

Does my version solves the very first problem you reported? I am not sure if `resolve()` is needed

**Comment by bcdiaconu** [comment]
> I suspect it's not needed since the `kid` and `parent` are already absolute with `os.sep`

Well, tests made on `Path` have shown differently (see [Path tests](https://github.com/nosarthur/gita/issues/215#issuecomment-1026563355) ). And the csv file contains some unnatural Windows path formats

> I think your test cases are a bit too unreal / strict.

Indeed the should be unreal. However, the real world showed they are quite real (see csv contents). And the strictness in testcases bring a working solution in a large set of real-world situation (which should indeed be unreal)

> Does my version solves the very first problem you reported?

I will try. I need to get back to job now. I'll get back to you later

**Comment by bcdiaconu** [comment]
> I will try. I need to get back to job now. I'll get back to you later

A PR with how you want your function to be integrated would be required, which I shall test on Windows side.

**Comment by nosarthur** [comment]
please try v0.16.2.1, it corresponds to PR #219

**Comment by bcdiaconu** [comment]
it look right

**Comment by bcdiaconu** [comment]
still some issues are with passing the path as an cli arg. different behaviour in passing `d:` and `d:\`

![image](https://user-images.githubusercontent.com/23461852/152185540-ec0ced1b-5d5b-4778-9a38-8691a03f9737.png)

**Comment by nosarthur** [comment]
what does `os.path.abspath` return for `d:` and `d:\` on your machine?

**Comment by nosarthur** [comment]
also, what does the top-level group look like in `~/.config/gita/group.csv` for `d:` and `d:\`?

**Comment by bcdiaconu** [comment]
I see you merged the PR so it seems it makes no sense to give further feedback

**Comment by nosarthur** [comment]
I merged it since it's already makes it better. We can still keep improving

According to this stackoverflow thread, `d:` means cwd on the `d` drive. Thus we are getting the expected result

https://stackoverflow.com/questions/66907726/why-is-the-absolute-path-of-a-drive-letter-equal-to-the-working-directory

**Comment by bcdiaconu** [comment]
> According to this stackoverflow thread, `d:` means cwd on the `d` drive. Thus we are getting the expected result

Indeed. Testing in `cmd`/`powershell` it turns out it is the `cwd` on the `d` drive. at the same time it seems that each drive has a working-directory and when switching the drive you switch the current working driectory to the working-directory of that drive. so indeed it is behaving correctly from that perspective.

but still there is an issue as seen below:
![image](https://user-images.githubusercontent.com/23461852/152357832-d82e8b63-499e-476e-bc62-8f309b8c4ba7.png)

**Comment by nosarthur** [comment]
Could you save the `~/.config/gita/groups.csv` in these two cases and see which 2 groups are missing?

Or we could stop here since `d:` is a somewhat problematic usage. Or I can match input `x:` and add `\` to them

**Comment by bcdiaconu** [comment]
the contents of the files are quite different. one more thing that might make a bit of light is that some groups (possibly all) have at least 1 entry like `  - -`. or in other words, a repo named `-` or a list inside a list

![image](https://user-images.githubusercontent.com/23461852/152366786-8addd8fc-6c93-462d-83f0-6bc5435386bd.png)

**Comment by nosarthur** [comment]
hmm, I am leaning towards leave it as is, or add `\` to `x:`. do you have any preference?

**Comment by bcdiaconu** [comment]
It is fine as is. The`\` will not solve anything.

The problem seems to be another issue altogether. I created the 220 issue for that
