### ISSUE TITLE
async calls for `gita ll`

### ISSUE THREAD

**Issue by nosarthur** [nosarthur/gita#22]
Retrieving status information from individual repos is [embarrassingly parallelizable](https://en.wikipedia.org/wiki/Embarrassingly_parallel).

Not sure if this would require a lot of changes though. Some commands are run with `os.system` and some with `subprocess`. Maybe it's not really worth the trouble ...

**Comment by seqizz** [comment]
Thanks for the async stuff, as a small feedback, you might want to use some progress bar (something like [progressbar2](https://pypi.org/project/progressbar2/)) instead of showing mixed output from all subprocesses, imho doesn't actually mean anything without an order anyway.

**Comment by nosarthur** [comment]
I need to think about how to do this. It seems output suppression (and potential progress bar) should only apply to `pull` and `fetch` if they are run asynchronously.

Right now, the code is structured such that if more than 1 `repo-name` is passed to `gita`, the corresponding command will be run asynchronously.

**Comment by nosarthur** [comment]
I think the execution stdout output are in finishing order (not mixed) now v0.8.0 (maybe since v0.7.7)

**Comment by seqizz** [comment]
Still, I currently have 10+ active repos registered and there is no way I'd follow which one ends where and other one starts :smile: Something short and informative would be easier to read.

```
reponame  branch  ###==== Updating...
reponame2  branch  ######## Failed (There is no tracking information for the current branch.)
reponame3  branch  ######## Done (2 new branches fetched, 1 file changed, 46 insertions(+))
reponame3  branch  ######## Done (Already up-to-date)
reponame4  branch  ######## Done (2 file changed, 12 insertions(+), 4 deletions(-))
```

I'll try to do something when I have time, if I can understand the codebase.

**Comment by nosarthur** [comment]
That looks quite nice (I always liked the display of `docker pull`). Let me create a new issue, meanwhile, this issue is not further pursued for now.
