### ISSUE TITLE
I am unable to remove a repository from a group if the repository does not exist anymore

### ISSUE THREAD

**Issue by pgrepds** [nosarthur/gita#225]
I had a repository that I have put into two groups. Let us call this repository `A`, then the command

```
gita group ll
```
returns

```
X:
 - A
Y:
 - A
```
I have deleted `A` from my disk and the command

```
gita ll
```
does not list `A` anymore. However, running

```
gita group ll
```
still lists `A`. I have tried executing the following command.

```
gita group rmrepo A -n X
```
which yields to the following message

```
gita group rmrepo: error: argument repo: invalid choice: 'A' (choose from ...)
```
I have tried running

```
gita rm A
```
which yields in the same error message.

What am I doing wrong? How can I remove `A` from my groups? 

Thank you very much for your help.

**Comment by nosarthur** [comment]
You did nothing wrong. It’s just that the group operations are unaware of any activities outside of gita and I didn’t check repo validity inside group operations as I did in repo operations.

For now, you can edit ~/.config/gita/groups.csv to remove the obsolete repo as a temporary fix

or run gita rm repo (which updates groups too) before rm -r repo 

in the near future, I will add a fix to check repo validity in group operations 

Same bug as in #211

**Comment by pgrepds** [comment]
Thank you for your quick response. Editing the config solved it for me!

**Comment by nosarthur** [comment]
please try 0.16.2.2
