### ISSUE TITLE
Starting again (or better option)

### ISSUE THREAD

**Issue by testfailagain** [nosarthur/gita#228]
Hi,

I change my project folder and now `gita ll` doesn't show anything.
I don't care a lot, so I tried to start again, I found the command `git clear`, but it said:
"gita: errro: invalid choice: 'clear' (choose from 'add', 'rm', 'freeze'.......)"

I don't know if it's because I don't have my gita repo updated (I don't know how to do that)
Or maybe the documentation is outdated, and you removed it in the new versions (I didn't installed it so long time ago)

Maybe there's a file where I can change the path, at the end It's like I move it from:
/home/bla/my_projects/projects....
to
/home/bla/projects/....

So, any solution is valid, clear all gita information and add it manually again, or a file to change the patch.

Thanks

**Comment by nosarthur** [comment]
`gita clear` should work. Maybe you don't have the latest gita installed. To upgrade

```
pip3 install -U gita
```
The repos and groups are saved in

```
~/.config/gita/repos.csv
~/.config/gita/groups.csv
```

**Comment by testfailagain** [comment]
correct, it was the version. problem solved, thanks.
