### ISSUE TITLE
Color printing does not work with Python 3.11 

### ISSUE THREAD

**Issue by elcorto** [nosarthur/gita#234]
Since 3.11 using `f"{Color.foo}"` prints `Color.foo` instead of inserting `Color.foo.value`. For instance:

```sh
$ gita ll -h
[...]
 branch colors:
    Color.whitewhiteColor.end: local has no remote
    Color.greengreenColor.end: local is the same as remote
    Color.redredColor.end: local has diverged from remote
    Color.purplepurpleColor.end: local is ahead of remote (good for push)
    Color.yellowyellowColor.end: local is behind remote (good for merge)
```

**Comment by nosarthur** [comment]
maybe CI hasn't been working for some time with my old workflow configs, now this color issue has been exposed, see

https://github.com/nosarthur/gita/actions/runs/4048236980/jobs/6963226705
