### ISSUE TITLE
dynamic groups based on status

### ISSUE THREAD

**Issue by mpatnode** [nosarthur/gita#237]
Any consideration on automatically generating dynamic groups based upon status.    For example:

1. I want to create a new branch in every repository which has changes
2. I want to run a rebase, followed by a force push in all repositories which become out of sync due to the rebase.

Theoretically, you might be able to work around this by extracting repository names from "gita ll"  via grep/awk, but that gets a little difficult when changes are displayed by color.  :-(

Another thought would be to have options on "gita ll" to only display repositories in a particular state (with or without colors).   Then you could parse out a list of repos and pass that to a super command line.    IE:

`gita super $(gita ll --staged | awk '{print $1}') commit -am 'implement a new feature'`

BTW: I assume there's a namespace restriction where a repository name can't be the same a git command?

**Comment by nosarthur** [comment]
`gita ll` actually has a `-C` option to suppress the colors

`--staged` seems like a good idea too

I never tried with such repo names, but there is probably no explicit checks

**Comment by nosarthur** [comment]
This is related to #168

**Comment by nosarthur** [comment]
I am closing this case since picking the staged repos can be achieved using bash tricks

```
 gita ll -C |rg ' \+ '| cut -d ' ' -f1
```
