### ISSUE TITLE
async call for git command execution

### ISSUE THREAD

**Issue by nosarthur** [nosarthur/gita#24]
`__main__.py` loops through `repos` and calls `exec_git`

**Comment by nosarthur** [comment]
I feel this is more useful than #22 since `gita ls` is not that slow, but `gita fetch` could be slow

**Comment by seqizz** [comment]
Ah yes, I came here to say we need some parallelism, since `gita super pull` would take a lot less time, but you already created the issue :grimacing: 

Btw I've submitted gita to the nixos repository :tada: thanks for this tool

**Comment by nosarthur** [comment]
Good to know that this is of interest, and thanks for exposing gita!

PS, in 0.7.3, you can do `gita pull` directly, it should be the same as `gita super pull`
