### ISSUE TITLE
show status as words as well as colour in `gita ll`

### ISSUE THREAD

**Issue by yellowtailfan** [nosarthur/gita#243]
It would be great if the status of each repo could be shown as a word as well as using colour. This would help when using the tool only occasionally because I wouldn't need to look up what the colours mean. It's good to still display the colour as well as it makes the altered repo states stand out.

Example (colour = status word -- meaning):
white = missing -- local has no remote
green = [blank] -- local is the same as remote
red = diverged -- local has diverged from remote
purple = ahead -- local is ahead of remote (good for push)
yellow = behind -- local is behind remote (good for merge)

This status word could be added as a new column next to the coloured column of active branch names.

**Comment by nosarthur** [comment]
Thanks, this is a good idea. I can add an information item and expose it to `gita info`

**Comment by tinder-cfuller** [comment]
@yellowtailfan Would symbols such as #245 work for you instead of words?

**Comment by yellowtailfan** [comment]
I think this is nicely dealt with in #245.
