### ISSUE TITLE
gita ll - nothing happend

### ISSUE THREAD

**Issue by ygol** [nosarthur/gita#249]
Hi,
I just install with 'pip3 install -U gita' under zsh ubuntu.
when doing 'gita' I get the help presented but 'gita ll' just returns a blank line and it seem the child repositories are not recognized
![image](https://github.com/nosarthur/gita/assets/2945174/03fa9a25-f9f5-4e69-83ff-21833877ee91)

Did I missed something maybe?
TIA

**Comment by nosarthur** [comment]
you have to add the repos to it, either add them one by one or add them recursively. See `gita add -h`

or you can check out this video
https://www.youtube.com/watch?v=ySWbwQcbhqI

**Comment by ygol** [comment]
Thank you @nosarthur
