### ISSUE TITLE
Adding groups doesn't work as in readme example

### ISSUE THREAD

**Issue by TamaMcGlinn** [nosarthur/gita#261]
The [readme](https://github.com/nosarthur/gita#define-repo-group-and-context) has this example:

```
gita group add repo1 repo2 -n my-group
```

But when I try this (after creating repo1 and repo2 git repos inside the current working dir), it gives me:

```
usage: gita group add [-h] -n group-name [-p group-path] repo [repo ...]
gita group add: error: argument repo: invalid choice: 'repo1' (choose from )
```

I also tried different orders of argument as suggested in the message:

```
$ gita group add -n my-group repo1 repo2
usage: gita group add [-h] -n group-name [-p group-path] repo [repo ...]
gita group add: error: argument repo: invalid choice: 'repo1' (choose from )
```

And also the example for auto-adding should work, since repo1 and repo2 are the only two git repos in my current working dir:

```
$ gita add -a my-group
No new repos found!
```

So... what can I do to debug? It kinda looks like the whole tool doesn't work for me.

```
$ gita --version
gita 0.16.6.4
```

**Comment by dzhou-schrodinger** [comment]
In order to use group command, the repos has to be added first

Checkbthe add sub command. There are options to recursively add and automatically group when adding repos

**Comment by TamaMcGlinn** [comment]
So, the gita add -a command should have worked?

**Comment by nosarthur** [comment]
the `gita add -a` generates groups automatically based on the folder structures (see the readme example), which may or may not be of the right grouping

`gita add -r` adds the repos without grouping them, then you can group according to your like
