### ISSUE TITLE
Limit `gita ll` column widths

### ISSUE THREAD

**Issue by elcorto** [nosarthur/gita#264]
Hi

Thanks for this project.

I have a question related to column widths in the `gita ll` output, using the current `master` (a5ba6fe).

* long repo names shift the output rather far to the right
* long branch names disturb the branch name + status column

```
very_very_very_very_long_repo_name_why_not     main     []    Commit mesage here (4 weeks ago)
a_repo                                         long-branch-name-here [] Commit mesage here (4 weeks ago)
another_repo                                   master   []    Commit mesage here, and some more long long text (4 weeks ago)
```

Is there a way to configure a max width per column?

I have an [experimental branch](https://github.com/elcorto/gita/tree/feature-ll-print-table) based off [a rather old master](https://github.com/nosarthur/gita/commit/63894703d53b30034161ef81171724bd2f3c9503). There I just [hard-coded some width quickly](https://github.com/elcorto/gita/blob/feature-ll-print-table/gita/utils.py#L543). I had to rewrite some code to separate the branch name and the branch state in order to apply the string length truncation only to the branch name. Not sure if this is still the case in the current code. I used [`tabulate`](https://github.com/astanin/python-tabulate) to help with the column printing, which looks like this:

```
repo                              head                     state    commit_msg                        commit_time
--------------------------------  -----------------------  -------  --------------------------------  -----------------------
very_very_very_very_long_repo_..  main                              Commit mesage here                (4 weeks ago)
a_repo                            long-branch-name-here             Commit mesage here                (4 weeks ago)
another_repo                      main                              Commit mesage here, and some m..  (4 weeks ago)
```

Separating branch name and state made it also possible [to support a `-d/--dirty` flag](https://github.com/elcorto/gita/blob/feature-ll-print-table/gita/__main__.py#L216-L218). Not sure if there is an equivalent feature in `master`. I also tried to use [`rich`](https://github.com/Textualize/rich) for table layout [but that didn't work that well](https://github.com/elcorto/gita/blob/feature-ll-print-table/gita/__main__.py#L222-L235), probably because of the color escape codes, but that's just a guess. Anyway that branch is rather different from current `master` by now and lacks nice features such as concurrent execution. Since it is difficult to rebase that branch onto current `master`, I was wondering if there is a way to truncate the column widths in the current code. Thanks a lot!

**Comment by nosarthur** [comment]
maybe the easy solution is to add an option for `gita ll` to limit the lengths for all columns

btw, one can also change repo name with `gita rename ...`. Gita treats the repo name and the repo path separately

**Comment by elcorto** [comment]
> maybe the easy solution is to add an option for `gita ll` to limit the lengths for all columns

Yes, or a config option. As mentioned I don't know how easy it would  be to support this if branch name + status are treated as one string, which was the case [when I last checked](https://github.com/nosarthur/gita/commit/63894703d53b30034161ef81171724bd2f3c9503). But looking at the current master, this seems to be separated now?

> btw, one can also change repo name with `gita rename ...`. Gita treats the repo name and the repo path separately

What does this do? The help text "rename the chosen repo" doesn't go into details. I *guess* it changes the name in the second column of `~/.config/gita/repos.csv`?

In both cases, having the names truncated of course assumes that the part of the name that's displayed is still unique and informative, but I guess here a configurable length will cover most use cases. Renaming (setting an alias?) with `gita` may be a workaround, but only for for repo names. Also in the repo case, I could rename the repo itself if a shorter name was possible.

**Comment by nosarthur** [comment]
please try 0.16.7.2

**Comment by elcorto** [comment]
Thanks a lot!

I tested this feature and would like to give some feedback.

```sh
$ gita info
In use: branch,commit_msg,commit_time
Unused: branch_name,path

$ cat ~/.config/gita/layout.csv
branch,symbols,branch_name,commit_msg,commit_time,path
19,5,27,0,0,30
```

`gita info` says I'm not using `branch_name` and `path`. I could not figure out what the difference between `branch` and `branch_name` is. Are those "information items" (from `gita info -h`) documented somewhere?

With the above settings, I get

```sh
$ gita ll
very_very_very_very_long_repo_name_why_not     main                    [] Commit mesage here (4 weeks ago)
a_repo                                         long-branch-name-h...   [] Commit mesage here (4 weeks ago)
another_repo                                   master                  [] Commit mesage here, and some more long long text (4 weeks ago)
```

The `branch` width seems to affect the branch name (2nd column), which is great. However, I found no way to truncate the repo name (first column). The only setting that sounds like this is `path` but according to `gita info` I'm not using this. Thanks.

**Comment by nosarthur** [comment]
Repo name is not an info item since it has to be displayed. It is out of the truncator mechanism currently

https://github.com/nosarthur/gita/blob/master/gita/utils.py#L419

**Comment by elcorto** [comment]
OK I see, thanks a lot.
