### ISSUE TITLE
gita hangs after 'gita pull' when password is needed for multiple repos

### ISSUE THREAD

**Issue by lstodd** [nosarthur/gita#42]
When I type 'gita pull', gita pulls the latest changes but then hangs and doesn't go back to the command line. Need to 'Ctrl + C' to escape. 

Exception ignored when trying to write to the signal wakeup fd:
OSError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "<venv>/bin/gita", line 11, in <module>
    load_entry_point('gita==0.8.4', 'console_scripts', 'gita')()
  File "<venv>/lib/python3.6/site-packages/gita/__main__.py", line 170, in main
    args.func(args)
  File "<venv>/lib/python3.6/site-packages/gita/__main__.py", line 73, in f_git_cmd
    utils.run_async(path, cmds) for path in repos.values())
  File "<venv>/lib/python3.6/site-packages/gita/utils.py", line 157, in exec_async_tasks
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/backup/Software/apps_rh/python-3.6/lib/python3.6/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/backup/Software/apps_rh/python-3.6/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/backup/Software/apps_rh/python-3.6/lib/python3.6/asyncio/base_events.py", line 1395, in _run_once
    event_list = self._selector.select(timeout)
  File "/backup/Software/apps_rh/python-3.6/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt

**Comment by nosarthur** [comment]
Can you add a screenshot of `gita ll`? And the `git remote -v` information for the repos? Thanks

Also, is it possible to narrow down the repos to see which one/ones causes this hang?

**Comment by nosarthur** [comment]
BTW, which version are you using?

**Comment by nosarthur** [comment]
Another diagnosis you can do is to add the following content to `~/.config/gita/cmds.yml`

```
pull:
  allow_all: true
  help: pull remote updates
  disable_async: true
```
And see if the hanging problem persists.

**Comment by lstodd** [comment]
I'm using gita==0.8.4.

I am using this at work so have blocked out some of the repo names/server names etc.

![image](https://user-images.githubusercontent.com/20112921/54274486-1f040b80-4580-11e9-8380-1718c63178c5.png)


`gita pull <repo name>` works fine. When I just do `gita pull` this is where it seems to hang. I usually type my password in each time I pull. Since I am pulling from 3 repos it asks for the password 3 times all at once, so I only have chance to type it twice - might this be the problem?

![image](https://user-images.githubusercontent.com/20112921/54275100-b584fc80-4581-11e9-96fc-957d00e5a7d3.png)

**Comment by nosarthur** [comment]
Yeah, that must be the problem. On one of my computers, I have ssh password-less login setup except one repo, and that seems to work. It must be the multiple repo password input.

A quick fix is to put the following in your `~/.config/gita/cmds.yml`

```
pull:
  allow_all: true
  disable_async: true
  help: pull remote updates
```
It disables the async execution, and the `gita pull` will block for password input for each repo.

Meanwhile I will look into how to block for stdin in the async execution. Thanks for the bug report

**Comment by lstodd** [comment]
Thanks for the quick fix! Works for me.

**Comment by nosarthur** [comment]
Hi, @lstodd I wonder if 0.8.9 automatically solve the issue for you, without defining custom command?

**Comment by lstodd** [comment]
Hi @nosarthur I still require the definition of pull in `~/.config/gita/cmds.yml` stated above.

Without it I get the following:

`Traceback (most recent call last):
  File "venv_path/bin/gita", line 11, in <module>
    load_entry_point('gita==0.10.2', 'console_scripts', 'gita')()
  File "venv_path/lib/python3.6/site-packages/gita/__main__.py", line 194, in main
    cmds = utils.get_cmds_from_files()
  File "venv_path/python3.6/site-packages/gita/utils.py", line 198, in get_cmds_from_files
    cmds.update(custom_cmds)
TypeError: 'NoneType' object is not iterable`

**Comment by nosarthur** [comment]
thanks for letting me know, which version did u try? the latest?

**Comment by nosarthur** [comment]
I made some minor change to skip empty custom `cmd.yml`. Can you try if `0.10.3` works for you? You don't need to delete `~/.config/gita/cmds.yml` with `0.10.3`
