### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by G3z** [nosarthur/gita#5]
Hello, I installed via pip3 (on a mac) and when I try to run it I get this error
```
$ gita
Traceback (most recent call last):
  File "/usr/local/bin/gita", line 7, in <module>
    from gita.__main__ import main
  File "/usr/local/lib/python3.7/site-packages/gita/__main__.py", line 2, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by aboyett** [comment]
`pyyaml` is specified as a dependency in [requirements.txt](https://github.com/nosarthur/gita/blob/master/requirements.txt#L6) but not referenced  in `setup.py` so pip has no knowledge of the stated dependency.

**Comment by langenhagen** [comment]
I got the same error, and would be happy to see a fix.

**Comment by G3z** [comment]
@langenhagen you can run `pip3 install -U pyyaml` until an official fix is released

**Comment by langenhagen** [comment]
@G3z , thank you for the idea. However, I as I use `pipsi` (https://github.com/mitsuhiko/pipsi) to maintain `Python` cli tools, I find it rather hacky apply this solution in my case. For now, I stick to a solution that I created myself :) However, I would like to see `gita` working. I find it quite neat.

**Comment by nosarthur** [comment]
Sorry for overlooking it. I will add requirements to `setup.py` later
