### ISSUE TITLE
Output showing escape code instead of being colored in Powershell

### ISSUE THREAD

**Issue by AndreasHae** [nosarthur/gita#51]
When using the `ll` command, the name of the branch is supposed to have a specific color based on its status.

In Powershell, this is not the case. Instead, it shows the escape sequence of the color, as seen in this screenshot:
![image](https://user-images.githubusercontent.com/14837928/54887737-aa41a300-4e96-11e9-96e4-333169b20225.png)

This was working correctly in version 0.6.5

**Comment by nosarthur** [comment]
which version has this problem? `0.8.7`?

**Comment by AndreasHae** [comment]
Yup, 0.8.7

**Comment by AndreasHae** [comment]
Just tried version 0.7, it worked fine there as well.

**Comment by nosarthur** [comment]
Weird. That part of the logic hasn't changed for a long time. Does the following snippet work on your machine?

```
purple = '\x1b[35m'
end = '\x1b[0m'

print(purple + 'this is purple color' + end)
```

**Comment by nosarthur** [comment]
Does `gita ll -h` show colors with version 0.8.7 on your machine?

**Comment by AndreasHae** [comment]
No, the snippet shows the same result.

Same problem with `gita ll -h`.

Really weird, because it worked fine with version 0.7.

**Comment by nosarthur** [comment]
What about this one?
```
print( "\033[31;1mError:\033[0m some message")
```

**Comment by nosarthur** [comment]
I found a solution on stackoverflow

https://stackoverflow.com/questions/51680709/colored-text-output-in-powershell-console-using-ansi-vt100-codes

**Comment by AndreasHae** [comment]
Thanks, the registry setting fixed it!
