### ISSUE TITLE
Better handling of KeyboardInterrupts

### ISSUE THREAD

**Issue by AndreasHae** [nosarthur/gita#52]
When the user wants to cancel e.g. the `ll` command using Ctrl+C, a stack trace is shown. This should be handled in a more user friendly way, hiding the stack trace away and maybe showing a message that the execution was cancelled.

**Comment by nosarthur** [comment]
- https://stackoverflow.com/questions/23826695/handling-keyboard-interrupt-when-using-subproccess
- https://vorpus.org/blog/control-c-handling-in-python-and-trio/

**Comment by nosarthur** [comment]
I feel this issue is not particularly useful.
