### ISSUE TITLE
Not able to add git worktree directory as repo

### ISSUE THREAD

**Issue by nagakiran** [nosarthur/gita#56]
Does gita can manage git worktree directories also?

I am using git worktrees to have different branches checked out into different directories at the same time. And would like to manage git worktree directories also with gita.

Tried, `gita add  <path-of-work-tree-dir>` but seeing the following error:
`No new repos found!`

**Comment by nosarthur** [comment]
I didn't know about `git worktree` before. But it doesn't seem hard to support it!
