### ISSUE TITLE
translate the information item customization document to Chinese

### ISSUE THREAD

**Issue by nosarthur** [nosarthur/gita#63]
In #59 the document in README.md is not fully translated to README_CN.md. Specifically, the information item customization is not translated.

**Comment by TpOut** [comment]
maybe i can do something.
how to contribute?

**Comment by nosarthur** [comment]
1. fork the repo
1. add translation to README_CN.md in your forked repo
1. make a pull request

The content to be translated is in #59 

You can also checkout tutorials:
https://github.com/collections/choosing-projects
https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/
 https://codeburst.io/a-step-by-step-guide-to-making-your-first-github-contribution-5302260a2940

**Comment by TpOut** [comment]
i have push a pull request
as a fisrt notice :

- some words seem to be translated by machine, like `branch` translated to `裤衩` which has special meaning in git. And i translate it to `分支`(common translate)， for we know it like a branch in tree.
- some words also like by machine, but has total different meaning when i put it in google-translating. -- so i wonder what the trans-machine is --  like 'commit ' to '贡献', ‘贡献’ maybe fit to 'contribute'
- some words i m not sure whether it is the most fit one, but it should not be a mistake. like commit message, 提交信息
- some words is not right here, like `staged` to `上台`, i translate it followed by git-book(https://git-scm.com/book/zh/v2/Git-%E5%B7%A5%E5%85%B7-%E4%BA%A4%E4%BA%92%E5%BC%8F%E6%9A%82%E5%AD%98) which is `暂存`
- some words are direct translated but should be translate with context. like `information items` to `信息项`， for i just translate and have not used this lib, so not change it now. But note for further.
- and some changes not be allowed (or just not communicate with u), u can just rechange them, it's ok.

terms:
- branch: 分支
- local: 本地
- remote: 远程
- repo: 库
- push: 推送
- merge: 合并
- stage: 暂存

some tips:
- for fist section:
>Gita is a single name, should not be translated to two words: Git 啊
- line 21(after): 
>the direct translate is ：`这个工具有两个作用：` . and the old one is ok , just like the install section. In my feel, the older just like a introduce to man , and not a tool.
- line 36(after):
>not sure if `using green as baseline` should be ahead of the links
- line 65(after):
>it is not fully translated ,but i also cant translate it.

the whole change is top to the first description of 'superman mode'
