### ISSUE TITLE
add 'group' sub-command

### ISSUE THREAD

**Issue by nosarthur** [nosarthur/gita#69]
I usually add many repos to gita and some of them are related. Right now all repos are sorted by name in the `gita ll` display. It'll look nicer if related repos are next to each other.

The `group` sub-command has the form of
```
gita group <repo-names>
```
It writes a group number into the `repo_path` file for bookkeeping. And the `gita ll` will look like

```
┌ repo1 new-feature arstarsta
│ repo2 new-feature arstarsta
└ repo3 new-feature arstarsta
   repo-x master arstarsta
   repo-xxx fix-bug arstarsta
┌ repo-y master arstarsta
└ repo-z master arstarsta
```

**Comment by nosarthur** [comment]
Maybe it's better to add both `group` and `setgroup`.

After `gita setgroup 1`, only group 1 repos will show. And use `gita setgroup` to unset

**Comment by deqing** [comment]
My case is more like [issue 71](https://github.com/nosarthur/gita/issues/71)

We have two big projects, "Client" and "Server", where some repos are shared. It is like:

    client-repo
    client-plugin1-repo
    client-plugin2-repo
    client-lib-repo
    common-lib-repo

    server-repo
    server-plugin1-repo
    server-lib-repo
    common-lib-repo

In this case, `git ll` might not easily present the relationships, I'd prefer something like:

    gita group client client-repo client-plugin1-repo ...
    gita group server server-repo server-plugin1-repo ...
    gita ll client

**Comment by nosarthur** [comment]
interesting, I haven't thought about one repo belonging to multiple groups before, but it definitely makes sense.

**Comment by rstacruz** [comment]
:+1: on this! I would think of them as tags, so I might have something like an `@work` and `@personal` tags... and I might have tags for `@ruby` and `@js`.

**Comment by nosarthur** [comment]
Yeah, tagging makes sense too. I haven't decided on what to do exactly yet...

**Comment by nosarthur** [comment]
Maybe something like this

```
gita tag a-repo b-repo <br>
> tag name? frontend
gita tag a-repo c-repo <br>
> tag name? secret
```
Here the user types in `frontend` and `secret` as tag names.

Then `gita ll` will show a, b, and c repos. `gita ll frontend` shows a and b. `gita ll secret` shows a and c.
