### ISSUE TITLE
Please use $XDG_CONFIG_HOME for keeping the configuration

### ISSUE THREAD

**Issue by seqizz** [nosarthur/gita#7]
Hi and thanks for this useful tool.

Would you consider putting .gita folder under $XDG_CONFIG_HOME instead of creating another folder directly under home?

**Comment by nosarthur** [comment]
I have no experience with $XDG_CONFIG_HOME before. My chromebook has this ENV var defined at 
```
/home/chronos/user/.config
```
But my macbook pro and office desktop with Centos 7 doesn't have it defined. What do you do if it's not defined?

**Comment by nosarthur** [comment]
I just read this wiki. It sounds good to me! Thanks for the suggestion!
https://wiki.archlinux.org/index.php/XDG_Base_Directory

**Comment by nosarthur** [comment]
please try version 0.6.8
let me know if there is further issues, thanks

**Comment by nosarthur** [comment]
I made some mistake in 0.6.8. Please try 0.6.9

**Comment by seqizz** [comment]
Thanks, I will when I see 0.6.9 in the releases/branches/tags. :+1:

**Comment by nosarthur** [comment]
It’s up
