### ISSUE TITLE
Suggest explicitly specifying encoding parameter when reading README.md in setup.py

### ISSUE THREAD

**Issue by MapleCCC** [nosarthur/gita#74]
Installation via `pip` fails for me. The error message implies that the `open` library function defaults to locale-related encoding scheme, which is `gbk` on my computer, and fails when encountering the Chinese characters in `README.md`. Less technologically-inclined people might feel clueless finding cause to the problem. So I suggest we explicitly specifying the encoding scheme `utf-8` when reading `README.md` in `setup.py`. The change, though small, might improve robustness.

PS: thank you for making such amazing tool!

**Comment by nosarthur** [comment]
Thanks for the report. It's surprising since there is no Chinese characters in `README.md`, at least not intended. I will double check.

**Comment by nosarthur** [comment]
I see, it must be the link to the Chinese version of README file.

**Comment by nosarthur** [comment]
Is this the change that made it work on your computer? In `setup.py`

`13      long_description=long_description,`

to

`13      long_description=long_description.encode('utf-8'),`

Also, would you be interested in submitting a pull request for this change? Then I can list you as a contributor?

**Comment by MapleCCC** [comment]
Hi, nosarthur, thank you for your kind reply. After testing, I find the Chinese character causing problem is exactly located at where you refer, that is, the link to the Chinese version of README.

The change that solves the problem on my side is to explicitly specify encoding argument as `UTF-8` in the `open` library function, like this:
```
long_description = None
with open('README.md', encoding='utf-8') as f:
    long_description = f.read()
```
Hope this help.

Since this is a very trivial change, I don't consider myself a meaningful contributor. It should be good enough for you to just make change directly without PR. But thanks for kind mentioning.

**Comment by MapleCCC** [comment]
By the way, I also try the fix you mention. It doesn't seem to resolve, since the exception I encounter is raised from the `open` library function when reading README.md, which is before the variable `long_description` is initialized.

**Comment by nosarthur** [comment]
Thanks. I have made the change you suggested in version 0.10.4. Please let me know if `pip3 install -U gita` works for you now

**Comment by MapleCCC** [comment]
Yes, it works. Thank you! I will close the issue then.
