### ISSUE TITLE
Subcommand to move to git repo directory

### ISSUE THREAD

**Issue by murarisumit** [nosarthur/gita#81]
I was using gita for a while, at-times I have move to git repo, if I have too many operation to perform on git repo. so was thinking to have a command by which which I can directly switch from anywhere to git repo.

Current workflow

```
gita ls <repo>
cd <repo>
```

Was thinking of having command like 
```
gita cd <repo>
```

What opinions do you guys have on it.

**Comment by nosarthur** [comment]
Currently I use 
```
cd `gita ls <repo>`
```

I am not sure if your proposal is doable, see here:

https://stackoverflow.com/questions/13732221/change-directory-with-python

**Comment by murarisumit** [comment]
thanks for pointing it out, sure it does make sense.
