### ISSUE TITLE
Workspace - specific repo configs

### ISSUE THREAD

**Issue by Javierieh** [nosarthur/gita#82]
Hey, first of all thanks for all the good work. You have saved me countless hours managing multi repo projects.

I was thinking of adding a feature to have workspace-specific repo configurations so different workspaces have different list of repos.

Should be pretty straightforward to implement via a recursive check for a ".gita" config file or similar.

More than happy to do a pull request for this what do you think?
Thanks.

**Comment by nosarthur** [comment]
Hi, Javierieh, thanks for your interest.

I recently added a `group` command. If you type `gita group repo1 repo2 repo3`, a group will be generated. Then `gita ll gp1` will only display the group with name `gp1`.

It should be relatively easy to allow all commands to take group names as input, but it's not done yet.

Is this similar to what's on your mind? I don't fully understand how your recursive check works. Suppose I am at a random folder, how do we know which config file to load?

**Comment by nosarthur** [comment]
In v0.10.8, the delegated git commands can take group names as input

**Comment by Javierieh** [comment]
Nice! This is almost exactly what I was looking for.
I was thinking that instead of specifying the group each time when issuing a command, you could have a .gita config file inside a folder. If your repos are within a single root workspace folder (which should be very common), that workspace folder could host the .gita file. Whenever you issue any gita command it can read from that file to determine what repos to filter for the commands.

It looks like I can achieve this behavior without modifying gita at all by building a small script that reads from parent folders recursively (until a .gita file is found) and using the group command, but it would be nice to have built in support for it.

If you think this idea is worth it I'm happy to do a PR.

**Comment by nosarthur** [comment]
This sounds like a good idea! Please go ahead with the PR. Thanks

A few questions when there is no workspace .gita config file:

- would it be much slower since we need to search all the way to user home for the config file?
- what if the repo or current path is not inside user home?
- should the workspace config file always be a subset of the user home config file?

Maybe we can add a `workspace` command. If no argument, it lists the existing workspace paths. If a path is provided as argument, it saves it to a config file. To trigger the workspace behavior, we can check if the current path is inside any registered workspace path.

Please let me know what you think. For the PR, please don’t worry about my suggestions.

**Comment by Javierieh** [comment]
Those are good points.

- Yeah the no .gita scenario would mean a busy search until you hit the root /. We could limit the search to the root of home directory
- In this case you would have to search until you get to root folder "/" which can mean a lot of searching for a non-existent file
- This will be a good way to avoid deep search scenarios but I think your workspace command suggestion works great too.

Adding the workspace command sounds like a great idea and it simplifies the logic. I'll give it a shot and we can discuss on the PR :)

**Comment by nosarthur** [comment]
I think `gita context` is the preferred approach since it's explicit

Labeling `wontfix`

**Comment by c33s** [comment]
as feedback i can say that the context with the group command are rather unhandy. also the global config don't have a good UX/DX, feels like a global git config without the option to have one per repo.

individual config files which are placed in the root of the main repo where gita should manage the repo itself and all/added subrepos would be so much more handy (relative paths would be important). it allows to easily manage the repo with its subrepos and also commit the config into the main repo so another developer don't have to setup the same thing again.

you are done after running these commands, where add adds the current path as main repo (a .gita file is created there) and the command `git ll` is automaticall scoped to this main repo. without defining groups and specifiing contexts.
```bash
gita add -r ./
gita ll
```

the global config feels really strange. why should work with mixed repos? got two puppet control repos with quite a lot subrepos. for me it has no benefit at all to have them combined in the global config with their absolute paths and then manually separating them into groups and then having to set the context where i can forget to change the context and work on the wrong project even if i am in the right folder.

please rething the `wont-fix`, having the context set by the dir where the `.gita` file resides and everything relevant for the project is inside this file.

**Comment by nosarthur** [comment]
I have a quick-and-dirty implementation in v0.13.5

```
gita add -m main-repo-path
```
would add sub-repos recursively

Let me know if you spot any bugs. I am still thinking of enhancing it furthur, see 

https://github.com/nosarthur/gita/projects/1

**Comment by nosarthur** [comment]
I am also curious how you guys organize file system for this repo inside repo situation. A bit of googling shows there are at least 3 ways

1. git submodule
2. use `.gitignore` to ignore the sub-repos
3. symbolic link to the sub-repos

Do you guys use one of them or some other ways?

**Comment by nosarthur** [comment]
please try v0.13.6

let me know if there is any bugs

**Comment by nosarthur** [comment]
I have added an `auto` context in 0.15.5

```
gita context auto
```

This will switch context, i.e., group, automatically depending on the current working directory so that any `git` action only applies to repos ini that group. It works on normal repos, untested with 'main repos'. I actually plan to remove the 'main repo'/local config mechanism
