### ISSUE TITLE
zsh的自动补全无法使用 / Auto completion for zsh is unavailable

### ISSUE THREAD

**Issue by Steve-Xyh** [nosarthur/gita#89]
# zsh的自动补全无效, 只有bash才能用
- 请问如何在zsh启用自动补全?

# Auto completion for zsh is unavailable, but it is available in bash.
- How can I activate auto-completion in zsh?

![image](https://user-images.githubusercontent.com/33098678/89120452-0e439500-d4e9-11ea-8c2e-4923ebc97b88.png)
![image](https://user-images.githubusercontent.com/33098678/89120472-2a473680-d4e9-11ea-9a82-991c514d3ccb.png)

**Comment by nosarthur** [comment]
I don't use zsh, so I don't know how zsh autocompletion is setup. A quick googling leads me to this article 

https://scriptingosx.com/2019/07/moving-to-zsh-part-5-completions/

It says

> You do not have to rewrite these completions, since the zsh completion system can use bash completion scripts as well: (add this to your zsh configuration file)

```
# load bashcompinit for some old bash completions
autoload bashcompinit && bashcompinit

[[ -r ~/Projects/autopkg_complete/autopkg ]] && source ~/Projects/autopkg_complete/autopkg
```

Let me know if it works.

If that fails, we may need a separate script for zsh. I suspect the change won't be big, see the following references

- https://mads-hartmann.com/2017/08/06/writing-zsh-completion-scripts.html
- https://github.com/nosarthur/gita/blob/master/.gita-completion.bash
- https://nosarthur.github.io/side%20project/2020/07/04/gita-milestone5.html

In the last link I briefly explained how the bash completion in gita is done.

**Comment by Steve-Xyh** [comment]
![image](https://user-images.githubusercontent.com/33098678/89128115-e1fa3980-d525-11ea-8017-916d80869da6.png)

Well...it still doesn't work.
And it showed this message after I source it
`complete:13: command not found: compdef`

---
![image](https://user-images.githubusercontent.com/33098678/89128134-ff2f0800-d525-11ea-939f-0f5d08f03f3b.png)
This is my .zprofile

**Comment by nosarthur** [comment]
See this thread

https://github.com/ohmyzsh/ohmyzsh/issues/3356

**Comment by Steve-Xyh** [comment]
![image](https://user-images.githubusercontent.com/33098678/89128977-f4777180-d52b-11ea-9d62-05f14731ea49.png)
Ummm.....I tried this method but it still has an error every time I create a new terminal window.
The global autocompletion for zsh works well, but still doesn't work for `gita`

**Comment by Steve-Xyh** [comment]
[zsh-completions doc](https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org)
[an article in zh-CN](https://blog.csdn.net/weixin_33963189/article/details/89602735)

It seems like the completion of zsh is quite different from bash 😳
