### ISSUE TITLE
Command for mass-clone

### ISSUE THREAD

**Issue by daniel-baumann** [nosarthur/gita#92]
Hi,

thank you so much for gita, it's a very nice tool.

The one thing I'm missing is a "clone" command. I'd like to have a list of URLs in the config file of gita, together with the location it should clone them on the filesystem. This would allow me to do a 'gita clone' which then would clone all these repositories (if not already existing).

Use-case: when re-installing a system, a 'gita clone' would be enough to be ready again.

Regards,
Daniel

**Comment by nosarthur** [comment]
Thanks @daniel-baumann 

It seems to be useful

**Comment by nosarthur** [comment]
I'm thinking of the following behaviors

## clone repos from a config file
```
gita clone config-file [-m]
```
-  Each row of the config file is a repo. It has remote address and local path.
-  By default, all repos are cloned to `cwd`. If `-m` is set, clone to the local path specified in the config file if possible. If not possible, still clone to `cwd`.
- After cloning, automatically add them to gita

## print current repos to stdout
```
gita freeze
```
- Print in the config file format

**Comment by nosarthur** [comment]
I only implemented the `freeze` command and 

```
gita clone config-file
```

All repos are clone to `cwd`. You will need to move them to their destinations maybe from a bash command. The old paths are saved in the `gita freeze` output
