### ISSUE TITLE
Add sub-commands for `gita group`

### ISSUE THREAD

**Issue by hamiltont** [nosarthur/gita#94]
IMO the command syntax is confusing - you have to pass a list of groups before you get any indication that a name will be requested. I spent 4-5min reading the help text thinking I was missing something, because there was no indication a name would be requested. 

At a minimum, update the help text to say "You will be prompted for the group name". However, ideally you woudl support a `--name` arg before the positional args, so the entire command could be scripted if needed

**Comment by nosarthur** [comment]
Thanks for the suggestion. Maybe it's better to add subcommand to `gita group` such as `add`, `rm`, etc

**Comment by hamiltont** [comment]
A sub-subcommand does make sense - `gita group ls`, `gita group add` , etc seems quite clear
